//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-06 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "D:\\Workspace\\MFES\\Project\\Cascade\\Cascade\\Cascade.rtf".

// ***** VDMTOOLS START Name=package KEEP=NO
package logic;
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class Cascade implements EvaluatePP {

// ***** VDMTOOLS START Name=board KEEP=NO
  public volatile Board board = null;
// ***** VDMTOOLS END Name=board

// ***** VDMTOOLS START Name=level KEEP=NO
  public volatile Number level = null;
// ***** VDMTOOLS END Name=level

// ***** VDMTOOLS START Name=score KEEP=NO
  public volatile Number score = null;
// ***** VDMTOOLS END Name=score

// ***** VDMTOOLS START Name=timeToNextLine KEEP=NO
  public volatile Number timeToNextLine = null;
// ***** VDMTOOLS END Name=timeToNextLine

// ***** VDMTOOLS START Name=isPlayable KEEP=NO
  public volatile Boolean isPlayable = null;
// ***** VDMTOOLS END Name=isPlayable

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=CascadeSentinel KEEP=NO
  class CascadeSentinel extends Sentinel {

    public final int play = 0;

    public final int Cascade = 1;

    public final int endGame = 2;

    public final int isVictory = 3;

    public final int nextLevel = 4;

    public final int nr_functions = 5;


    public CascadeSentinel () throws CGException {}


    public CascadeSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=CascadeSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new CascadeSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel

// ***** VDMTOOLS START Name=MinNumber KEEP=NO
  public static final Number MinNumber = new Integer(3);
// ***** VDMTOOLS END Name=MinNumber

// ***** VDMTOOLS START Name=NLinesNextLevel KEEP=NO
  public static final Number NLinesNextLevel = new Integer(10);
// ***** VDMTOOLS END Name=NLinesNextLevel

// ***** VDMTOOLS START Name=maxLevel KEEP=NO
  public static final Number maxLevel = new Integer(15);
// ***** VDMTOOLS END Name=maxLevel


// ***** VDMTOOLS START Name=vdm_init_Cascade KEEP=NO
  private void vdm_init_Cascade () {
    try {
      setSentinel();
      board = new Board();
      level = new Integer(1);
      score = new Integer(0);
      timeToNextLine = UTIL.NumberToInt(new Integer((int)(1000 * (8 - (level.intValue() * 0.5)))));
      isPlayable = Boolean.TRUE;
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_Cascade


// ***** VDMTOOLS START Name=inv_Cascade KEEP=NO
  public Boolean inv_Cascade () {
    Boolean rexpr_8 = null;
    Boolean var1_9 = null;
    if ((var1_9 = Boolean.valueOf(level.intValue() > 0)).booleanValue()) 
      var1_9 = Boolean.valueOf(level.intValue() <= (maxLevel.intValue() + 1));
    if ((rexpr_8 = var1_9).booleanValue()) 
      rexpr_8 = Boolean.valueOf(score.intValue() >= 0);
    return rexpr_8;
  }
// ***** VDMTOOLS END Name=inv_Cascade


// ***** VDMTOOLS START Name=CalculateScore#1|Number KEEP=NO
  private Number CalculateScore (final Number n_blocks) throws CGException {
    if (!this.pre_CalculateScore(n_blocks).booleanValue()) 
      UTIL.RunTime("Precondition failure in CalculateScore");
    if (!this.post_CalculateScore(n_blocks, UTIL.NumberToInt(new Integer(50 + (20 * (n_blocks.intValue() - 3))))).booleanValue()) 
      UTIL.RunTime("Postcondition failure in CalculateScore");
    return UTIL.NumberToInt(new Integer(50 + (20 * (n_blocks.intValue() - 3))));
  }
// ***** VDMTOOLS END Name=CalculateScore#1|Number


// ***** VDMTOOLS START Name=pre_CalculateScore#1|Number KEEP=NO
  private Boolean pre_CalculateScore (final Number n_blocks) throws CGException {
    return Boolean.valueOf(n_blocks.intValue() >= MinNumber.intValue());
  }
// ***** VDMTOOLS END Name=pre_CalculateScore#1|Number


// ***** VDMTOOLS START Name=post_CalculateScore#2|Number|Number KEEP=NO
  private Boolean post_CalculateScore (final Number n_blocks, final Number RESULT) throws CGException {
    return Boolean.valueOf(RESULT.intValue() >= 50);
  }
// ***** VDMTOOLS END Name=post_CalculateScore#2|Number|Number


// ***** VDMTOOLS START Name=Cascade KEEP=NO
  public Cascade () throws CGException {
    try {
      vdm_init_Cascade();
      new NewLineThread(this).start();
      new NextLevelThread(this).start();
      setSentinel();
    }
    catch (Throwable e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=Cascade


// ***** VDMTOOLS START Name=play#1 KEEP=NO
  public Number play (final Board.Position pos) throws CGException {
    sentinel.entering(((CascadeSentinel)sentinel).play);
    try {
      Number n_pieces = board.deletePieces(pos);
      Boolean cond_3 = null;
      if ((cond_3 = Boolean.valueOf(n_pieces.intValue() >= 3)).booleanValue()) 
        cond_3 = isPlayable;
      if (cond_3.booleanValue()) {
        score = new Integer(score.intValue() + CalculateScore(n_pieces).intValue());
        if (!this.inv_Cascade().booleanValue()) 
          UTIL.RunTime("Instance invariant failure in Cascade");
        return CalculateScore(n_pieces);
      }
      else 
        return new Integer(0);
    }
    finally {
      sentinel.leaving(((CascadeSentinel)sentinel).play);
    }
  }
// ***** VDMTOOLS END Name=play#1


// ***** VDMTOOLS START Name=nextLevel KEEP=NO
  public Boolean nextLevel () throws CGException {
    sentinel.entering(((CascadeSentinel)sentinel).nextLevel);
    try {
      if (!this.pre_nextLevel().booleanValue()) 
        UTIL.RunTime("Precondition failure in nextLevel");
      level = new Integer(level.intValue() + 1);
      if (!this.inv_Cascade().booleanValue()) 
        UTIL.RunTime("Instance invariant failure in Cascade");
      Number rhs_11 = new Double(1000 * (8 - (level.intValue() * 0.5)));
      if (!UTIL.IsNat(((Object)rhs_11))) 
        UTIL.RunTime("Incompatible type");
      timeToNextLine = UTIL.NumberToInt(UTIL.clone(rhs_11));
      if (!this.inv_Cascade().booleanValue()) 
        UTIL.RunTime("Instance invariant failure in Cascade");
      if (level.intValue() == (maxLevel.intValue() + 1)) {
        isPlayable = Boolean.FALSE;
        if (!this.inv_Cascade().booleanValue()) 
          UTIL.RunTime("Instance invariant failure in Cascade");
        return Boolean.FALSE;
      }
      return Boolean.TRUE;
    }
    finally {
      sentinel.leaving(((CascadeSentinel)sentinel).nextLevel);
    }
  }
// ***** VDMTOOLS END Name=nextLevel


// ***** VDMTOOLS START Name=pre_nextLevel KEEP=NO
  public Boolean pre_nextLevel () throws CGException {
    return isPlayable;
  }
// ***** VDMTOOLS END Name=pre_nextLevel


// ***** VDMTOOLS START Name=endGame KEEP=NO
  public void endGame () throws CGException {
    sentinel.entering(((CascadeSentinel)sentinel).endGame);
    try {
      if (!this.pre_endGame().booleanValue()) 
        UTIL.RunTime("Precondition failure in endGame");
      isPlayable = Boolean.FALSE;
      if (!this.inv_Cascade().booleanValue()) 
        UTIL.RunTime("Instance invariant failure in Cascade");
    }
    finally {
      sentinel.leaving(((CascadeSentinel)sentinel).endGame);
    }
  }
// ***** VDMTOOLS END Name=endGame


// ***** VDMTOOLS START Name=pre_endGame KEEP=NO
  public Boolean pre_endGame () throws CGException {
    return isPlayable;
  }
// ***** VDMTOOLS END Name=pre_endGame


// ***** VDMTOOLS START Name=isVictory KEEP=NO
  public Boolean isVictory () throws CGException {
    sentinel.entering(((CascadeSentinel)sentinel).isVictory);
    try {
      if (!this.pre_isVictory().booleanValue()) 
        UTIL.RunTime("Precondition failure in isVictory");
      if (level.intValue() == (maxLevel.intValue() + 1)) 
        return Boolean.TRUE;
      else 
        return Boolean.FALSE;
    }
    finally {
      sentinel.leaving(((CascadeSentinel)sentinel).isVictory);
    }
  }
// ***** VDMTOOLS END Name=isVictory


// ***** VDMTOOLS START Name=pre_isVictory KEEP=NO
  public Boolean pre_isVictory () throws CGException {
    return Boolean.valueOf(!isPlayable.booleanValue());
  }
// ***** VDMTOOLS END Name=pre_isVictory

}
;
