//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-08 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package logic;
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class external_MATH {

// ***** VDMTOOLS START Name=parent KEEP=NO
  MATH parent = null;
// ***** VDMTOOLS END Name=parent


// ***** VDMTOOLS START Name=external_MATH#1|MATH KEEP=NO
  public external_MATH (MATH parentMATH) {
    parent = parentMATH;
  }
// ***** VDMTOOLS END Name=external_MATH#1|MATH


// ***** VDMTOOLS START Name=external_MATH KEEP=NO
  public external_MATH () {}
// ***** VDMTOOLS END Name=external_MATH


// ***** VDMTOOLS START Name=impl_sin#1|Number KEEP=NO
  public Number impl_sin (final Number v) throws CGException {
    UTIL.RunTime("Preliminary Function sin has been called");
    return new Double(0);
  }
// ***** VDMTOOLS END Name=impl_sin#1|Number


// ***** VDMTOOLS START Name=impl_cos#1|Number KEEP=NO
  public Number impl_cos (final Number v) throws CGException {
    UTIL.RunTime("Preliminary Function cos has been called");
    return new Double(0);
  }
// ***** VDMTOOLS END Name=impl_cos#1|Number


// ***** VDMTOOLS START Name=impl_tan#1|Number KEEP=NO
  public Number impl_tan (final Number a) throws CGException {
    UTIL.RunTime("Preliminary Function tan has been called");
    return new Double(0);
  }
// ***** VDMTOOLS END Name=impl_tan#1|Number


// ***** VDMTOOLS START Name=impl_cot#1|Number KEEP=NO
  public Number impl_cot (final Number a) throws CGException {
    UTIL.RunTime("Preliminary Function cot has been called");
    return new Double(0);
  }
// ***** VDMTOOLS END Name=impl_cot#1|Number


// ***** VDMTOOLS START Name=impl_asin#1|Number KEEP=NO
  public Number impl_asin (final Number a) throws CGException {
    UTIL.RunTime("Preliminary Function asin has been called");
    return new Double(0);
  }
// ***** VDMTOOLS END Name=impl_asin#1|Number


// ***** VDMTOOLS START Name=impl_acos#1|Number KEEP=NO
  public Number impl_acos (final Number a) throws CGException {
    UTIL.RunTime("Preliminary Function acos has been called");
    return new Double(0);
  }
// ***** VDMTOOLS END Name=impl_acos#1|Number


// ***** VDMTOOLS START Name=impl_atan#1|Number KEEP=NO
  public Number impl_atan (final Number v) throws CGException {
    UTIL.RunTime("Preliminary Function atan has been called");
    return new Double(0);
  }
// ***** VDMTOOLS END Name=impl_atan#1|Number


// ***** VDMTOOLS START Name=impl_sqrt#1|Number KEEP=NO
  public Number impl_sqrt (final Number a) throws CGException {
    UTIL.RunTime("Preliminary Function sqrt has been called");
    return new Double(0);
  }
// ***** VDMTOOLS END Name=impl_sqrt#1|Number


// ***** VDMTOOLS START Name=impl_pi_f KEEP=NO
  public Number impl_pi_f () throws CGException {
    UTIL.RunTime("Preliminary Function pi_f has been called");
    return new Double(0);
  }
// ***** VDMTOOLS END Name=impl_pi_f


// ***** VDMTOOLS START Name=impl_rand#1|Number KEEP=NO
  public Number impl_rand (final Number a) throws CGException {
    UTIL.RunTime("Preliminary Operation rand has been called");
    return new Integer(0);
  }
// ***** VDMTOOLS END Name=impl_rand#1|Number


// ***** VDMTOOLS START Name=impl_srand2#1|Number KEEP=NO
  public Number impl_srand2 (final Number a) throws CGException {
    UTIL.RunTime("Preliminary Operation srand2 has been called");
    return new Integer(0);
  }
// ***** VDMTOOLS END Name=impl_srand2#1|Number


// ***** VDMTOOLS START Name=impl_exp#1|Number KEEP=NO
  public Number impl_exp (final Number a) throws CGException {
    UTIL.RunTime("Preliminary Function exp has been called");
    return new Double(0);
  }
// ***** VDMTOOLS END Name=impl_exp#1|Number


// ***** VDMTOOLS START Name=impl_ln#1|Number KEEP=NO
  public Number impl_ln (final Number a) throws CGException {
    UTIL.RunTime("Preliminary Function ln has been called");
    return new Double(0);
  }
// ***** VDMTOOLS END Name=impl_ln#1|Number


// ***** VDMTOOLS START Name=impl_log#1|Number KEEP=NO
  public Number impl_log (final Number a) throws CGException {
    UTIL.RunTime("Preliminary Function log has been called");
    return new Double(0);
  }
// ***** VDMTOOLS END Name=impl_log#1|Number


// ***** VDMTOOLS START Name=impl_fac#1|Number KEEP=NO
  public Number impl_fac (final Number a) throws CGException {
    UTIL.RunTime("Preliminary Function fac has been called");
    return new Integer(1);
  }
// ***** VDMTOOLS END Name=impl_fac#1|Number

}
;
